// HPWEB JAVASCRIPT hpweb_country_pulldown.js VERSION 1.0

	// Store URLs in an array. These must match the elements in the
	//  pulldown. In this example, the first element is the pulldown
	//  says 'Select a URL', thus countrySelect_URLs[0] contains an empty
	//  string. Note in this case that the name of the URL array
	//  is mapped to that of the Menu. This is assumed in the
	//  function below.

var countrySelect_URLs = new Array();
countrySelect_URLs[0] = "";
countrySelect_URLs[1] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Africa  //
// countrySelect_URLs[2] = "http://thenew.hp.com/country/me/eng/international_gateway.html"; //  Algeria  //
// countrySelect_URLs[2] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Angola  //
countrySelect_URLs[2] = "http://thenew.hp.com/country/ar/spa/welcome.html"; //  Argentina  //
// countrySelect_URLs[5] = "http://thenew.hp.com/country/ap/eng/international_gateway.html"; //  Asia Pacific  //
countrySelect_URLs[3] = "http://thenew.hp.com/country/au/eng/welcome.html"; //  Australia  //
countrySelect_URLs[4] = "http://thenew.hp.com/country/at/ger/welcome.html"; //  Austria  //
// countrySelect_URLs[6] = "http://www.hp.com/middleeast/"; //  Bahrain  //
// countrySelect_URLs[7] = "http://ap.compaq.com.sg/southasia/"; //  Bangladesh  //
countrySelect_URLs[5] = "http://www.compaq.be/"; //  Belgium  //
// countrySelect_URLs[9] = "http://ap.compaq.com.sg/southasia/"; //  Bhutan  //
countrySelect_URLs[6] = "http://thenew.hp.com/country/bo/spa/international_gateway.html"; //  Bolivia  //
// countrySelect_URLs[11] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Botswana  //
countrySelect_URLs[7] = "http://thenew.hp.com/country/br/por/welcome.html"; //  Brazil  //
// countrySelect_URLs[13] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Burundi  //
countrySelect_URLs[8] = "http://thenew.hp.com/country/bg/bul/international_gateway.html"; //  Bulgaria  //
countrySelect_URLs[9] = "http://thenew.hp.com/country/ca/eng/welcome.html"; //  Canada  //
countrySelect_URLs[10] = "http://welcome.hp.com/country/ns/eng/welcome.htm"; //  Caribbean  //
// countrySelect_URLs[17] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Central African Republic  //
countrySelect_URLs[11] = "http://welcome.hp.com/country/ns/spa/welcome.htm"; //  Central America  //
countrySelect_URLs[12] = "http://thenew.hp.com/country/cl/spa/international_gateway.html"; //  Chile  //
countrySelect_URLs[13] = "http://thenew.hp.com/country/cn/chi/welcome.html"; //  China  //
countrySelect_URLs[14] = "http://thenew.hp.com/country/co/spa/international_gateway.html"; //  Colombia  //
// countrySelect_URLs[22] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Congo  //
// countrySelect_URLs[23] = "http://welcome.hp.com/country/ns/spa/welcome.htm"; //  Costa Rica  //
countrySelect_URLs[15] = "http://thenew.hp.com/country/hr/cro/international_gateway.html"; //  Croatia  //
// countrySelect_URLs[25] = "http://www.hp.com/middleeast/"; //  Cyprus  //
countrySelect_URLs[16] = "http://thenew.hp.com/country/cz/cze/international_gateway.html"; //  Czech Republic  //
countrySelect_URLs[17] = "http://thenew.hp.com/country/dk/dan/welcome.html"; //  Denmark  //
// countrySelect_URLs[18] = "http://welcome.hp.com/country/ns/spa/welcome.htm"; //  Dominican Republic  //
countrySelect_URLs[18] = "http://thenew.hp.com/country/ec/spa/international_gateway.html"; //  Ecuador  //
// countrySelect_URLs[30] = "http://www.hp.com/middleeast/"; //  Egypt  //
// countrySelect_URLs[31] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Erithrea  //
// countrySelect_URLs[32] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Ethiopia  //
countrySelect_URLs[19] = "http://thenew.hp.com/country/ee/est/international_gateway.html"; //  Estonia  //
countrySelect_URLs[20] = "http://thenew.hp.com/country/fi/fin/welcome.html"; //  Finland  //
countrySelect_URLs[21] = "http://thenew.hp.com/country/fr/fre/international_gateway.html"; //  France  //
// countrySelect_URLs[36] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Gabon  //
countrySelect_URLs[22] = "http://thenew.hp.com/country/de/ger/international_gateway.html"; //  Germany  //
// countrySelect_URLs[38] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Ghana  //
countrySelect_URLs[23] = "http://thenew.hp.com/country/gr/gre/welcome.html"; //  Greece  //
// countrySelect_URLs[24] = "http://welcome.hp.com/country/ns/spa/welcome.htm"; //  Guatemala  //
countrySelect_URLs[24] = "http://thenew.hp.com/country/hk/chi/welcome.html"; //  Hong Kong  //
countrySelect_URLs[25] = "http://thenew.hp.com/country/hu/hun/international_gateway.html"; //  Hungary  //
countrySelect_URLs[26] = "http://thenew.hp.com/country/in/eng/welcome.html"; //  India  //
countrySelect_URLs[27] = "http://thenew.hp.com/country/id/eng/international_gateway.html"; //  Indonesia  //
countrySelect_URLs[28] = "http://thenew.hp.com/country/ie/eng/international_gateway.html"; //  Ireland  //
countrySelect_URLs[29] = "http://thenew.hp.com/country/il/heb/international_gateway.html"; //  Israel  //
countrySelect_URLs[30] = "http://thenew.hp.com/country/it/ita/welcome.html"; //  Italy  //
// countrySelect_URLs[48] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Ivory Coast  //
countrySelect_URLs[31] = "http://thenew.hp.com/country/jp/jpn/international_gateway.html"; //  Japan  //
// countrySelect_URLs[50] = "http://www.hp.com/middleeast/"; //  Jordan  //
// countrySelect_URLs[51] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Kenya  //
countrySelect_URLs[32] = "http://thenew.hp.com/country/kr/kor/welcome.html"; //  Korea  //
// countrySelect_URLs[53] = "http://www.hp.com/middleeast/"; //  Kuwait  //
countrySelect_URLs[33] = "http://thenew.hp.com/country/lv/lat/international_gateway.html"; //  Latvia  //
// countrySelect_URLs[55] = "http://www.hp.com/middleeast/"; //  Lebanon  //
// countrySelect_URLs[56] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Liberia & Sierra Leone  //
countrySelect_URLs[34] = "http://thenew.hp.com/country/lt/lit/international_gateway.html"; //  Lithuania  //
countrySelect_URLs[35] = "http://thenew.hp.com/country/be/fre/international_gateway.html"; //  Luxembourg  //
// countrySelect_URLs[59] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Malawi  //
countrySelect_URLs[36] = "http://thenew.hp.com/country/my/eng/international_gateway.html"; //  Malaysia  //
// countrySelect_URLs[61] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Mauritius  //
countrySelect_URLs[37] = "http://thenew.hp.com/country/mx/spa/welcome.html"; //  Mexico  //
countrySelect_URLs[38] = "http://www.hp.com/middleeast/"; //  Middle East  //
// countrySelect_URLs[66] = "http://thenew.hp.com/country/aa/fre/international_gateway.html"; //  Morocco  //
// countrySelect_URLs[64] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Mozambique  //
// countrySelect_URLs[65] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Namibia  //
// countrySelect_URLs[66] = "http://ap.compaq.com.sg/southasia/"; //  Nepal  //
countrySelect_URLs[39] = "http://thenew.hp.com/country/nl/dut/welcome.html"; //  Netherlands  //
countrySelect_URLs[40] = "http://thenew.hp.com/country/nz/eng/welcome.html"; //  New Zealand  //
// countrySelect_URLs[69] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Nigeria  //
countrySelect_URLs[41] = "http://thenew.hp.com/country/no/nor/welcome.html"; //  Norway  //
// countrySelect_URLs[71] = "http://www.hp.com/middleeast/"; //  Oman  //
// countrySelect_URLs[72] = "http://ap.compaq.com.sg/southasia/"; //  Pakistan  //
// countrySelect_URLs[73] = "http://welcome.hp.com/country/ns/spa/welcome.htm"; //  Panama  //
countrySelect_URLs[42] = "http://thenew.hp.com/country/py/spa/international_gateway.html"; //  Paraguay  //
countrySelect_URLs[43] = "http://thenew.hp.com/country/pe/spa/international_gateway.html"; //  Peru  //
countrySelect_URLs[44] = "http://thenew.hp.com/country/ph/eng/welcome.html"; //  Philippines  //
countrySelect_URLs[45] = "http://thenew.hp.com/country/pl/pol/welcome.html"; //  Poland  //
countrySelect_URLs[46] = "http://thenew.hp.com/country/pt/por/welcome.html"; //  Portugal  //
countrySelect_URLs[47] = "http://thenew.hp.com/country/pr/spa/international_gateway.html"; //  Puerto Rico  //
// countrySelect_URLs[80] = "http://www.hp.com/middleeast/"; //  Qatar //
// countrySelect_URLs[81] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Republic of Congo //
countrySelect_URLs[48] = "http://thenew.hp.com/country/ro/rom/international_gateway.html"; //  Romania  //
countrySelect_URLs[49] = "http://www.hp.ru/"; //  Russia  //
// countrySelect_URLs[84] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Rwanda  //
countrySelect_URLs[50] = "http://thenew.hp.com/country/sa/eng/international_gateway.html"; //  Saudi Arabia  //
// countrySelect_URLs[89] = "http://www.hp.com/middleeast/"; //  Senegal  //
// countrySelect_URLs[86] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Seychelles  //
countrySelect_URLs[51] = "http://thenew.hp.com/country/sg/eng/welcome.html"; //  Singapore  //
countrySelect_URLs[52] = "http://thenew.hp.com/country/sk/slk/international_gateway.html"; //  Slovak Republic  //
countrySelect_URLs[53] = "http://thenew.hp.com/country/si/slv/international_gateway.html"; //  Slovenia  //
// countrySelect_URLs[90] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Somalia  //
countrySelect_URLs[54] = "http://thenew.hp.com/country/za/eng/international_gateway.html"; //  South Africa  //
countrySelect_URLs[55] = "http://ap.compaq.com.sg/southasia/"; //  South Asia  //
countrySelect_URLs[56] = "http://thenew.hp.com/country/es/spa/welcome.html"; //  Spain  //
// countrySelect_URLs[94] = "http://ap.compaq.com.sg/southasia/"; //  Sri Lanka  //
// countrySelect_URLs[95] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Swaziland  //
countrySelect_URLs[57] = "http://thenew.hp.com/country/se/swe/international_gateway.html"; //  Sweden  //
countrySelect_URLs[58] = "http://thenew.hp.com/country/ch/ger/welcome.html"; //  Switzerland  //
countrySelect_URLs[59] = "http://thenew.hp.com/country/tw/chi/welcome.html"; //  Taiwan  //
// countrySelect_URLs[99] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Tanzania  //
countrySelect_URLs[60] = "http://thenew.hp.com/country/th/eng/international_gateway.html"; //  Thailand  //
// countrySelect_URLs[105] = "http://www.hp.com/middleeast/"; //  Tunisia  //
countrySelect_URLs[61] = "http://thenew.hp.com/country/tr/tur/international_gateway.html"; //  Turkey  //
// countrySelect_URLs[102] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Uganda  //
countrySelect_URLs[62] = "http://thenew.hp.com/country/ua/ukr/international_gateway.html"; //  Ukraine  //
// countrySelect_URLs[104] = "http://www.hp.com/middleeast/"; //  United Arab Emirates  //
countrySelect_URLs[63] = "http://thenew.hp.com/country/uk/eng/welcome.html"; //  United Kingdom  //
countrySelect_URLs[64] = "http://thenew.hp.com/country/us/eng/welcome.html"; //  United States  //
countrySelect_URLs[65] = "http://thenew.hp.com/country/uy/spa/international_gateway.html"; //  Uruguay  //
countrySelect_URLs[66] = "http://thenew.hp.com/country/ve/spa/international_gateway.html"; //  Venezuela  //
countrySelect_URLs[67] = "http://thenew.hp.com/country/vn/eng/international_gateway.html"; //  Vietnam  //
// countrySelect_URLs[110] = "http://www.hp.com/middleeast/"; //  Yemen  //
// countrySelect_URLs[111] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Zambia  //
// countrySelect_URLs[112] = "http://welcome.hp.com/country/aa/eng/welcome.htm"; //  Zimbabwe //
countrySelect_URLs[68] = "http://thenew.hp.com/country/us/eng/othercountrieswel.html"; //  Other Country  //